logging.level:
  root: INFO
  org.springframework.boot: ERROR
  org.springframework.web: INFO
  org:
    springframework:
      web:
        filter:
          CommonsRequestLoggingFilter: OFF
  org.jooq.tools.LoggerListener: OFF
  org.jooq.Constants: OFF


spring:
  main:
    banner-mode: "off"